"""
main.py — Helm Runtime Service

FastAPI service that routes agent role requests to the correct model backend
via LiteLLM. Provider-agnostic. All model and provider configuration lives in
config.yaml. No hardcoded URLs, keys, or model names in this file.

Endpoints:
  POST /invoke/{agent_role}  — Route request to configured model, return response
  GET  /health               — Service up + all model endpoints + Supabase reachable
  GET  /config/agents        — Current agent-to-model mapping (no secrets)

BA7a: Service skeleton with stubbed agent handlers.
      Routing, middleware pipeline, health check, and config endpoint are active.
      Actual model calls to Projectionist/Archivist are wired in BA7b/BA7c.
"""

import logging
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

from fastapi import FastAPI, HTTPException, Path as FastAPIPath
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from agents import archivist as archivist_agent
from agents import contemplator as contemplator_agent
from agents import projectionist as projectionist_agent
from agents import speaker as speaker_agent
from embedding_client import EmbeddingClient
from middleware import InvokeRequest, MiddlewarePipeline, PrimeDirectivesViolation
from model_router import ConfigError, ModelRouter, UnknownRoleError
from supabase_client import SupabaseClient

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Service globals — initialized at startup
# ---------------------------------------------------------------------------

CONFIG_PATH = Path(__file__).parent / "config.yaml"

router: ModelRouter = None
supabase: SupabaseClient = None
pipeline: MiddlewarePipeline = None
embedding_client: EmbeddingClient = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialize service globals at startup. Fail fast on config errors."""
    global router, supabase, pipeline, embedding_client

    logger.info("Helm Runtime Service starting...")

    try:
        router = ModelRouter(str(CONFIG_PATH))
    except ConfigError as e:
        logger.critical("Configuration error at startup: %s", e)
        raise SystemExit(1) from e

    supabase = SupabaseClient(
        url=router.supabase_url,
        service_key=router.supabase_service_key,
    )

    if router.embedding_api_key:
        embedding_client = EmbeddingClient(
            api_key=router.embedding_api_key,
            model=router.embedding_model,
        )
        logger.info("EmbeddingClient initialized. model=%s", router.embedding_model)
    else:
        logger.warning(
            "Embeddings not configured — Archivist writes will not include embeddings. "
            "Add embeddings block to config.yaml to enable semantic search."
        )

    pipeline = MiddlewarePipeline()

    logger.info("Helm Runtime Service ready.")
    yield

    logger.info("Helm Runtime Service shutting down.")


# ---------------------------------------------------------------------------
# FastAPI app
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Helm Runtime Service",
    description=(
        "Provider-agnostic agent orchestration layer. "
        "Routes Helm agent role requests to the correct model backend."
    ),
    version="0.1.0",
    lifespan=lifespan,
)


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------

class InvokeRequestBody(BaseModel):
    session_id: str = Field(..., description="UUID generated by Claude Code at session start")
    turn_number: int = Field(..., ge=0, description="Turn counter from TURN_COUNT")
    user_message: str = Field(..., description="Verbatim user message — no truncation")
    helm_response: str = Field(..., description="Verbatim Helm Prime response — no truncation")
    context: dict = Field(
        default_factory=lambda: {"project": "hammerfall-solutions", "agent": "helm"},
        description="Project and agent scope for brain writes",
    )


class InvokeResponse(BaseModel):
    role: str
    output: str
    session_id: str
    turn_number: int


# ---------------------------------------------------------------------------
# Agent handlers — BA7a stubs
# BA7b wires Projectionist. BA7c wires Archivist.
# ---------------------------------------------------------------------------

async def _handle_projectionist(req: InvokeRequest) -> str:
    """Route to Projectionist handler — frame creation via qwen3:4b on Ollama."""
    return await projectionist_agent.handle(req, router, supabase)


async def _handle_archivist(req: InvokeRequest) -> str:
    """Route to Archivist handler — frame migration with embedding via qwen3:14b on Ollama."""
    return await archivist_agent.handle(req, router, supabase, embedding_client)


async def _handle_contemplator(req: InvokeRequest) -> str:
    """
    Contemplator — Helm's inner life. S1-BA3.

    session_start: Pass 1 only, think=False (~10s, non-blocking).
                   Returns curiosity flags for Helm Prime Routine 0.
    session_end:   Pass 1 + Pass 2, think=True (~30s, deep synthesis).
                   Returns full write payload, then triggers Archivist
                   write handoff (belief patches, patterns, flags, reflection).

    Trigger is read from req.context["trigger"]. Defaults to "session_end".
    """
    import json as _json

    result_str = await contemplator_agent.handle(req, router, supabase)
    result = _json.loads(result_str)

    # session_end: hand off write payload to Archivist
    if result.get("trigger") == "session_end" and result.get("status") == "session_end_complete":
        payload = result.get("payload", {})
        if payload:
            write_req = InvokeRequest(
                session_id=req.session_id,
                turn_number=req.turn_number,
                user_message=req.user_message,
                helm_response=req.helm_response,
                context={**req.context, "contemplator_writes": payload},
            )
            await archivist_agent.handle(write_req, router, supabase, embedding_client)
            logger.info(
                "Contemplator→Archivist write handoff complete. session=%s", req.session_id
            )

    return result_str


async def _handle_speaker(req: InvokeRequest) -> str:
    """
    Speaker routing — S1-BA1.
    Classifies request as simple (resolve locally via Qwen2.5 3B) or complex
    (escalate to Helm Prime). Classification failure defaults to Helm Prime.
    See agents/speaker.py for full implementation.
    """
    return await speaker_agent.handle(req, router, supabase)


async def _handle_helm_prime(req: InvokeRequest) -> str:
    """
    Helm Prime runs on Claude Code, not the runtime. This endpoint exists for
    completeness and future use (e.g. Hammerfall Cloud routing Helm Prime calls).
    """
    return f"[STUB] Helm Prime invocation via runtime. Future use."


AGENT_HANDLERS = {
    "projectionist": _handle_projectionist,
    "archivist": _handle_archivist,
    "speaker": _handle_speaker,
    "helm_prime": _handle_helm_prime,
    "contemplator": _handle_contemplator,
}


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.post("/invoke/{agent_role}", response_model=InvokeResponse)
async def invoke(
    agent_role: str = FastAPIPath(..., description="Agent role to invoke"),
    body: InvokeRequestBody = ...,
) -> InvokeResponse:
    """
    Route a request to the model configured for agent_role.
    Runs the full middleware pipeline (pre → handler → post).
    """
    # Confirm the role is configured
    try:
        router.get_agent_config(agent_role)
    except UnknownRoleError as e:
        raise HTTPException(status_code=404, detail={"error": "unknown_role", "detail": str(e)})

    # Confirm we have a handler
    handler = AGENT_HANDLERS.get(agent_role)
    if not handler:
        raise HTTPException(
            status_code=404,
            detail={"error": "unknown_role", "detail": f"No handler for role: {agent_role}"},
        )

    # Build internal request object
    req = InvokeRequest(
        session_id=body.session_id,
        turn_number=body.turn_number,
        user_message=body.user_message,
        helm_response=body.helm_response,
        context=body.context,
    )

    # Pre-model middleware → agent handler → post-model middleware
    # Single outer try/except ensures PrimeDirectivesViolation is caught
    # regardless of which pipeline stage raises it. Pre-model was previously
    # unguarded — a guard trip there would have returned HTTP 500 instead of 403.
    try:
        req = pipeline.run_pre(agent_role, req)
        output = await handler(req)
        output = pipeline.run_post(agent_role, output)
    except PrimeDirectivesViolation as e:
        logger.warning(
            "Prime Directive violation blocked request: %s — %s", e.directive, e.detail
        )
        return JSONResponse(
            status_code=403,
            content={
                "error": "prime_directive_violation",
                "directive": e.directive,
                "detail": e.detail,
            },
        )
    except ValueError as e:
        # Validation failures from output_validator (malformed Projectionist frame)
        raise HTTPException(
            status_code=422,
            detail={"error": "validation_failed", "detail": str(e)},
        )
    except Exception as e:
        logger.exception("Agent handler error for role '%s': %s", agent_role, e)
        raise HTTPException(
            status_code=500,
            detail={"error": "handler_error", "detail": str(e)},
        )

    return InvokeResponse(
        role=agent_role,
        output=output,
        session_id=body.session_id,
        turn_number=body.turn_number,
    )


@app.get("/health")
async def health() -> JSONResponse:
    """
    Service health check. Checks three things:
      1. Runtime service is up (trivially true if this endpoint responds)
      2. All configured model endpoints are reachable
      3. Supabase REST API is reachable and helm_frames is queryable

    Returns HTTP 200 in all cases — status field indicates healthy/degraded.
    HTTP 500 is reserved for the health endpoint itself failing (runtime crash).
    """
    checks: dict[str, Any] = {"service": "ok", "models": {}, "supabase": {}}
    overall = "healthy"

    # Check each configured model
    for role in ("projectionist", "archivist", "helm_prime", "speaker", "contemplator"):
        try:
            result = await router.check_model_health(role)
            checks["models"][role] = result
            if result["status"] != "ok":
                overall = "degraded"
        except Exception as e:
            checks["models"][role] = {"status": "error", "error": str(e)}
            overall = "degraded"

    # Check Supabase
    sb_ok = await supabase.health_check()
    if sb_ok:
        checks["supabase"] = {"status": "ok", "table": "helm_frames", "rows_queryable": True}
    else:
        checks["supabase"] = {
            "status": "unreachable",
            "error": "Could not query helm_frames table",
        }
        overall = "degraded"

    return JSONResponse(content={"status": overall, "checks": checks})


@app.get("/config/agents")
async def config_agents() -> JSONResponse:
    """
    Return the current agent-to-model mapping.
    No secrets exposed — provider type, model name, and base URL only.
    API keys are intentionally omitted.
    """
    return JSONResponse(content={"agents": router.config_summary()})
